### ISSUE TITLE
verbose mode

### ISSUE THREAD

**Issue by jschueller** [ronivaldo/nopip#1]
when using nopip in an interactive session, we dont see any output, it could be great to add a verbose keyword to see the pip output in the console
also when an error occurs we dont have the stderr either

maybe something like
```
def run_pip_command(command, verbose=False):
       try:
            output = subprocess.run([sys.executable, "-m", "pip"] + command,
                                check=True, capture_output=verbose).stdout.decode()
        except subprocess.CalledProcessError as cpe:
            output = cpe.stdout.decode() + cpe.stderr.decode()
        if verbose:
            print(output)
```

**Comment by ronivaldo** [comment]
Hello,

Thank you for bringing this issue to our attention and for your detailed implementation suggestion. Your proposal has been reviewed and incorporated into the latest version of `nopip`.

In version `0.2.0`, we have introduced a `verbose` parameter in our `run_pip_command` method. With this new feature, users can choose to see the output from pip commands directly in the console during their interactive sessions. This should greatly facilitate debugging and enhance usability, especially when errors occur, as both `stdout` and `stderr` will be displayed if `verbose` is enabled.

The update is now available for download via PyPI. To get the new version, simply update the package using pip:

```bash
pip install nopip --upgrade
```

I hope the new functionality meets your needs! If you have more feedback or suggestions, please do not hesitate to open another issue.

Best regards,
Ronivaldo

**Comment by jschueller** [comment]
Thanks a lot
