### ISSUE TITLE
pythonw executable

### ISSUE THREAD

**Issue by jschueller** [ronivaldo/nopip#2]
on windows when running GUI linked to Python sys.executable is not the Python interpreter but the GUI executable, in that case one must use the pythonw.exe executable instead (also valid for non-guis):
```
def run_pip_command(command):
        python_exe = sys.executable
        if sys.platform.startswith("win"):
            python_exe = os.path.join(sys.prefix, "pythonw.exe")
        subprocess.check_call([python_exe, ...
```

**Comment by ronivaldo** [comment]
Hello,

Thank you for your report. We have addressed the issue with running `nopip` on Windows GUI environments in the latest release, version `0.2.0`. Now, the `run_pip_command` method correctly utilizes `pythonw.exe` when running on Windows to ensure proper execution.

Please update to the latest version by running:
```bash
pip install nopip --upgrade
```

If you encounter any further issues or have additional feedback, feel free to let us know.

Best regards,
Ronivaldo
