### ISSUE TITLE
new patch release

### ISSUE THREAD

**Issue by jschueller** [ronivaldo/nopip#5]
sorry to bother you again
would it be possible to get a new version on pypi that includes the capture fix (https://github.com/ronivaldo/nopip/pull/4) ?

**Comment by ronivaldo** [comment]
@jschueller The PyPI version of the project was updated on the release date. Please check it here:
https://pypi.org/project/nopip/

**Comment by ronivaldo** [comment]
Sorry, you are correct. The patch was missing, now it is OK. Thank you for the help
https://pypi.org/project/nopip/0.2.2/

**Comment by jschueller** [comment]
thanks a lot
